version: 2

jobs:
  test-client:
    machine: true
    steps:
      - checkout
      - run: make test-client

  test-contracts:
    machine: true
    steps:
      - checkout
      - run: make test-contracts

  test-hub:
    machine: true
    steps:
      - checkout
      - run: make test-hub

  test-e2e:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            make start
            git clone https://github.com/ConnextProject/card.git
            cd card
            make test-prod

  push-images:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make push

  push-live-images:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make push-live

  deploy-staging:
    machine: true
    steps:
      - run:
          command: |
            ssh ubuntu@$STAGING_URL "bash -s" <<EOF
              git clone https://github.com/ConnextProject/indra.git || true
              cd indra
              git fetch
              git reset --hard origin/$CIRCLE_BRANCH
              export INDRA_MODE="staging"
              export INDRA_ETH_NETWORK="rinkeby"
              export INDRA_DOMAINNAME="$STAGING_URL"
              bash ops/restart.sh prod
            EOF

  deploy-live:
    machine: true
    steps:
      - run:
          command: |
            ssh ubuntu@$RINKEBY_URL "bash -s" <<EOF
              git clone https://github.com/ConnextProject/indra.git || true
              cd indra
              git fetch
              git reset --hard origin/master
              export INDRA_DOMAINNAME="$RINKEBY_URL"
              export INDRA_ETH_NETWORK="rinkeby"
              export INDRA_MODE="live"
              bash ops/restart.sh prod
            EOF
            ssh ubuntu@$MAINNET_URL "bash -s" <<EOF
              git clone https://github.com/ConnextProject/indra.git || true
              cd indra
              git fetch
              git reset --hard origin/master
              export INDRA_DOMAINNAME="$MAINNET_URL"
              export INDRA_ETH_NETWORK="mainnet"
              export INDRA_MODE="live"
              bash ops/restart.sh prod
            EOF

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-client
      - test-contracts
      - test-hub
      # - test-e2e
      - push-images:
          requires:
            - test-client
            - test-contracts
            - test-hub
            # - test-e2e
      - push-live-images:
          filters:
            branches:
              only: master
          requires:
            - test-client
            - test-contracts
            - test-hub
            # - test-e2e
      - deploy-staging:
          filters:
            branches:
              ignore: master
          requires:
            - push-images
      - deploy-live:
          filters:
            branches:
              only: master
          requires:
            - push-live-images
