version: 2

jobs:
  test-client:
    machine: true
    steps:
      - checkout
      - run: make test-client

  test-contracts:
    machine: true
    steps:
      - checkout
      - run: make test-contracts

  test-hub:
    machine: true
    steps:
      - checkout
      - run: make test-hub

  test-e2e:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            time make start-test
            git clone https://github.com/ConnextProject/card.git
            cd card
            time make proxy-test
            time make test-prod

  push-latest-images:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make push-latest

  push-live-images:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: make push-live

  deploy-staging:
    machine: true
    steps:
      - run:
          command: |
            ssh ubuntu@$STAGING_URL "bash -s" <<EOF
              git clone https://github.com/ConnextProject/indra.git || true
              cd indra
              git fetch
              git reset --hard origin/$CIRCLE_BRANCH
              export INDRA_MODE="staging"
              export INDRA_ETH_NETWORK="rinkeby"
              export INDRA_DOMAINNAME="$STAGING_URL"
              export MAILGUN_API_KEY="$MAILGUN_API_KEY"
              bash ops/restart.sh prod
              docker container prune -f
              docker image ls -q | xargs docker image rm || true
            EOF

  deploy-live:
    machine: true
    steps:
      - run:
          command: |
            ssh ubuntu@$RINKEBY_URL "bash -s" <<EOF
              git clone https://github.com/ConnextProject/indra.git || true
              cd indra
              git fetch
              git reset --hard origin/master
              export MAILGUN_API_KEY="$MAILGUN_API_KEY"
              export INDRA_DOMAINNAME="$RINKEBY_URL"
              export INDRA_ETH_NETWORK="rinkeby"
              export INDRA_MODE="live"
              bash ops/restart.sh prod
              docker container prune -f
              docker image ls -q | xargs docker image rm || true
            EOF
            ssh ubuntu@$MAINNET_URL "bash -s" <<EOF
              git clone https://github.com/ConnextProject/indra.git || true
              cd indra
              git fetch
              git reset --hard origin/master
              export INDRA_DOMAINNAME="$MAINNET_URL"
              export INDRA_ETH_NETWORK="mainnet"
              export INDRA_MODE="live"
              export MAILGUN_API_KEY="$MAILGUN_API_KEY"
              bash ops/restart.sh prod
              docker container prune -f
              docker image ls -q | xargs docker image rm || true
            EOF

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-client
      - test-contracts
      - test-hub
      - test-e2e

      - push-latest-images:
          filters:
            branches:
              only: staging
          requires:
            - test-client
            - test-contracts
            - test-hub
            - test-e2e

      - push-live-images:
          filters:
            branches:
              only: master
          requires:
            - test-client
            - test-contracts
            - test-hub
            - test-e2e

      - deploy-staging:
          filters:
            branches:
              only: staging
          requires:
            - push-latest-images

      - deploy-live:
          filters:
            branches:
              only: master
          requires:
            - push-live-images
