image:
  repository: ''
ingress:
  enabled: true
  host: hub.spankchain.com
  tlsSecret: spankchain-ssl

resources:
  limits:
    cpu: 1
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 150Mi

local:
  postgresql: false
  skipDbMigrate: false

pgHost: ''
pgSecretName: ''

env:
  ETH_RPC_URL: ''
  NODE_ENV: ''
  WALLET_ADDRESS: ''
  HOT_WALLET_ADDRESS: ''
  SERVICE_USER_KEY: ''
  CHANNEL_MANAGER_ADDRESS: ''
  TOKEN_CONTRACT_ADDRESS: ''
  SHOULD_COLLATERALIZE_URL: ''
  COINPAYMENTS_MERCHANT_ID: ''
  COINPAYMENTS_API_KEY: ''

# Environment variabes retrieved from secrets.
#
#   FOO: 'bar.baz'
#
# Means "Set environment variable FOO to the 'baz' key in secret 'bar'."
env_secrets:
  COINPAYMENTS_API_SECRET: ''
  COINPAYMENTS_IPN_SECRET: ''

redis:
  usePassword: false
